# デフォルト有効で無効にするルール
disabled_rules:
  - file_length
  - function_body_length
  - type_body_length
  - cyclomatic_complexity
  - identifier_name
  - type_name

# デフォルト無効で有効にするルール
opt_in_rules:
  - include_bare_init
  - first_where

# 対象のファイル・フォルダ
included:
  - BuyByFriends

# 対象外のファイル・フォルダ
excluded:
  - .swiftpm

line_length:
  warning: 300
  error: 500

nesting:
  type_level:
    warning: 2
    error: 3
